### PR TITLE
Add reboot to install mode command

### PR DESCRIPTION
**Pull request by kiya956**
impact:
    sanity/agent/agent.py
    sanity/launcher/parser.py

description:
    add reboot to install mode command, we are not using EOF to do this
    due to it could casue hang as reboot did.

test:
    N/A

### CODE REVIEW

**Comment by stanley31huang** [comment]
the changes looks fine to me, but could you please write a unit test for a new method for run_stage?

**Review by tsunghanliu — COMMENTED** [review]
LGTM, but please make sure that we have enough test.

**Review by stanley31huang — APPROVED** [review]
LGTM

**Review by stanley31huang — APPROVED** [review]
LGTM

**Review by tsunghanliu — APPROVED** [review]

**Pull request merged**
